info:
  profile: dev
  dataSource: localhost:3306

server:
  port: {cipher}AQB/QGp8UN99sXVu0uvbrE4ZWUv2iIcl8iJslT4Gdgl+Ym5d8y65MdK85Tjib2Eq3nERhVyXxBwL2SByxxV78zMzAwyfhXRthA8fRmQ0vBW8XLVlvkppQUBcdXemk6nmRSGhUPhrn3pSSwIGccW9mjMbf0mSE6lUghLF0mru4lPsXibslbdFduLbIzdvJu/GNli1w+dyLFR2TOTX5S4/xZwaqUWZSW/hOtwl0axRJc8neHXVkA9wSqaW+aQZoeoDzByiW9o2eelh60cfpnaFXZpPne9caa4DZRHydyPz35tfK2kWQxuO3dl1EvLM3SoWgnnrtnUZHABhDJySZEYeJiP0A+BeIFKmqz8qchjmP3kHdtFouqG7PjQoP9yL8u0L3YE=
